eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: gateway

jwt:
  secret: askjfhKASKHAFFslkhafnlfAdnladhgognvFDLBNHoweutgjBlakjDGDsrladk

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: EMPLOYEE
          uri: lb://employee
          predicates:
            - Path=/api/v1/employee/**
          filters:
            - AuthFilter

        - id: ADDRESS
          uri: lb://address
          predicates:
            - Path=/api/v1/address/**
          filters:
            - AuthFilter

        - id: AUTH
          uri: lb://auth
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthFilter